timeout: 1800s
steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ['build', '-t', 'asia.gcr.io/$PROJECT_ID/chrome-headless:$TAG_NAME', 'chrome/.']
    id: "build-chrome-gcr"
  - name: "gcr.io/cloud-builders/docker"
    args: ['build', '-t', 'asia.gcr.io/$PROJECT_ID/websocketapi:$TAG_NAME', 'proxy_api/.']
    id: "build-proxy-gcr"
  - name: "gcr.io/cloud-builders/docker"
    args: ['push', 'asia.gcr.io/$PROJECT_ID/websocketapi:$TAG_NAME']
    id: "push-proxy-gcr"
  - name: "gcr.io/cloud-builders/docker"
    args: ['push', 'asia.gcr.io/$PROJECT_ID/chrome-headless:$TAG_NAME']
    id: "push-chrome-gcr"  
  - name: "asia.gcr.io/dazzling-byway-187403/mb8"
    args: ['mb8', '-t', '$TAG_NAME', '-f', "./k8s"]
    id: "mb8"  
  - name: "gcr.io/cloud-builders/kubectl"
    args: ["apply", "-f", "k8s"]
    env:
      - "CLOUDSDK_COMPUTE_ZONE=asia-east1-a"
      - "CLOUDSDK_CONTAINER_CLUSTER=ez-demo-1"
tags:
  - "chrome-headless"  
